server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: 1234
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache           #생략 가능

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
 
  security:
    oauth2:
      client:
        registration:
         google:
           client-id: 325140624710-snq2bt948qb57mgj67d93fig76ha8nvg.apps.googleusercontent.com
           client-secret: Od1ZooKhaBao6oWmSoex9aFw
           scope:
            - email
            - profile
              
         facebook:
           client-id: 295756068947101
           client-secret: c77af7ffdda180227b387439d5344958
           scope:
            - email
            - public_profile
              
       